services:

  microros-agent:
    image: microros/micro-ros-agent:humble
    container_name: microros
    privileged: true
    network_mode: host
    ipc: host
    volumes:
      - /dev:/dev 
      - /dev/shm:/dev/shm
    devices:
      - /dev/ttyAMA1
    command: serial --dev /dev/ttyAMA1 -b 576000 -v6